[build]
publish = "public"
command = "pnpm run build"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "20"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "pnpm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.148.2"
NODE_VERSION = "20"

[context.branch-deploy]
command = "pnpm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.148.2"
NODE_VERSION = "20"
